site_description: "Vue.js - Trực quang, Nhanh và có khả năng tích hợp với MVVM để xây dựng giao diện có tính tương tác cao."
google_analytics: UA-52973734-7
root_domain: vuejs.senviet.org
vue_version: 2.1.10
